# Generated by Django 6.0.3 on 2026-03-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_destinasi', models.CharField(max_length=100)),
                ('bintang_destinasi', models.IntegerField()),
                ('deskripsi_destinasi', models.TextField()),
                ('gambar_destinasi', models.ImageField(upload_to='destinasi_images/')),
            ],
        ),
    ]
